services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    user: "1000:1000" # Garante que o contêiner rode como francisco
    volumes:
      - /home/francisco:/srv
      - ../services/filebrowser/config/filebrowser.db:/database.db # Mapeia o diretório de configuração
      - ../services/filebrowser/config/filebrowser.json:/filebrowser.json # Mapeia o arquivo do banco de dados
    ports:
      - "48082:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    restart: unless-stopped
