
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /:/srv
      - ~/filebrowser/config:/config
      - ~/filebrowser/filebrowser.db:/database.db \
      - ~/filebrowser/.filebrowser.json:/.filebrowser.json \
    ports:
      - "48082:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    restart: unless-stopped
