---
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Recife
      - SETTINGS_ENCRYPTION_KEY="8caracteresalfanumericos-altere"
      - CLI_ARGS= #optional
      - DUPLICATI__WEBSERVICE_PASSWORD= #optional
    volumes:
      - ../services/duplicati/config:/config
      - ../services/duplicati/backups:/backups
      - /media:/media
      - /home:/home
    ports:
      - 8200:8200
    restart: unless-stopped
