services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "30080:80/tcp"
      - "30443:443/tcp"
      - "3000:3000/tcp"
    volumes:
      - ../services/adguardhome/work:/opt/adguardhome/work
      - ../services/adguardhome/conf:/opt/adguardhome/conf
      - ./services/adguardhome/cert:/cert
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    #networks:
    #  - adguard_network

networks:
  adguard_network:
    driver: bridge
