version: '3'
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetunbr
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - .env
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ADDRESSES=10.2.0.2/32
      - WIREGUARD_PUBLIC_KEY=ECpPKv2/sxck/VZIcVVk+0FZfZIe9PkXI1Lcpf9KODU=
      - WIREGUARD_ENDPOINT_IP=146.70.98.130
      - WIREGUARD_ENDPOINT_PORT=51820
      - DNS_ADDRESS=10.2.0.1
      - TZ=America/Sao_Paulo
    ports:
      - 1082:1080/tcp
    restart: unless-stopped

  socks5:
    image: serjs/go-socks5-proxy:latest
    container_name: socks5br
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped
