---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Recife
    volumes:
      - ~/docker/radarr:/config
      - /mnt:/mnt #optional
      - /media:/media
      
      
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Recife
    volumes:
      - ~/docker/sonarr:/config
      - /mnt:/mnt #optional
      - /media:/media
    ports:
      - 8989:8989
    restart: unless-stopped


  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Recife
    volumes:
      - ~/docker/lidarr:/config
      - /mnt:/mnt #optional
      - /media:/media
    ports:
      - 8686:8686
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Recife
    volumes:
      - ~/docker/prowlarr:/config
      - /mnt:/mnt #optional
      - /media:/media
    ports:
      - 9696:9696
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Recife
    volumes:
      - ~/docker/bazarr:/config
      - /mnt:/mnt #optional
      - /media:/media
    ports:
      - 6767:6767
    restart: unless-stopped
