services:
  protonvpn-livros:
    image: docker.io/qmcgaw/gluetun:v3.41.3
    container_name: protonvpn-livros
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file: .env
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - VPN_PORT_FORWARDING=${VPN_PORT_FORWARDING}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'sleep 60 && /usr/bin/wget -O- --retry-connrefused --tries=30 --waitretry=10 --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:${QBITTORRENT_WEBUI_PORT}/api/v2/app/setPreferences 2>&1'
    volumes:
      - ./vpn:/gluetun
    ports:
      - ${QBITTORRENT_WEBUI_PORT}:${QBITTORRENT_WEBUI_PORT}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "https://1.1.1.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true

  qbittorrent-livros:
    image: lscr.io/linuxserver/qbittorrent:5.2.3-libtorrentv1
    container_name: qbittorrent-livros
    depends_on:
      protonvpn-livros:
        condition: service_healthy
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
    volumes:
      - ../services/qbittorrent-livros/config:/config
      - /media/:/media/
      - /home/:/home/
      - /media/barracuda/downloads:/downloads
    network_mode: "service:protonvpn-livros"
    restart: unless-stopped
